Some bindings for RuntimeEffect
JetBrains/skija pull request #124
Opened 2021-07-30 12:42 UTC by Vechro

I tried to add some basic bindings for RuntimeEffect but I think I need some advice on how to proceed.

1. How should I handle the Result struct in RuntimeEffect.h? Should I also be returning one in Java?
2. That MakeShader binding is a mess, I have no idea how to deal with `childrenPtrs` and `uniformPtr`.
3. Are there any more RuntimeEffect functions that need bindings?

I'd appreciate any feedback, C++ isn't my strong suit.

Reference material:
* https://skia.org/docs/user/sksl/
* https://github.com/mono/SkiaSharp/pull/1221/files#diff-9b53ac31984a05ad45ba4e2d111d9dc89289422983199bc68a2512ee750da04cR2896
* https://skia.googlesource.com/skia/+/refs/heads/main/modules/canvaskit/canvaskit_bindings.cpp#1727

2021-07-30 18:57 UTC, tonsky commented
Hi, thanks for the contribution!

I’ll try to familiriaze myself with RuntimeEffect next week and see if I can help

2021-08-06 18:55 UTC, tonsky requested changes
Looks good, great start! I have a few notes

2021-08-06 18:55 UTC, tonsky commented on platform/cc/RuntimeEffect.cc
> +                                                     jlong childCount,
No need to pass count explicitly, java arrays already have count

2021-08-06 18:55 UTC, tonsky commented on platform/cc/RuntimeEffect.cc
> +    jfloat* m = env->GetFloatArrayElements(localMatrixArr, 0);
Consider using skija::skMatrix, it does what you do here + handles null pointer in the place of an array

2021-08-06 18:55 UTC, tonsky commented on platform/cc/RuntimeEffect.cc
> +    sk_sp<SkShader>* children = new sk_sp<SkShader>[childCount];
This array will leak. Consider using std::vector instead

2021-08-06 18:55 UTC, tonsky commented on platform/cc/RuntimeEffect.cc
> +    SkShader** cPtrs = reinterpret_cast<SkShader**>(childrenPtrs);
This won’t fly. Java arrays are not C arrays, unfortunately. You need to request special access to them. You need env->GetLongArrayElements, paired with ReleaseLongArrayElements after the loop. Each individual long can then be cast to pointer using jlongToPtr

2021-08-06 18:55 UTC, tonsky commented on platform/cc/RuntimeEffect.cc
> +    return ptrToJlong(&shader);
should be `ptrToJlong(shader.release())`

2021-08-06 18:55 UTC, tonsky commented on platform/cc/RuntimeEffect.cc
> +    SkRuntimeEffect::Result result = SkRuntimeEffect::MakeForColorFilter(skslProper);
Check for error and throw java exception in case of a failure

2021-08-06 18:55 UTC, tonsky commented on shared/java/RuntimeEffect.java
> +        long childCount = children == null ? 0 : children.length;
make it int, will save you a cast on the next line

2021-08-06 19:01 UTC, tonsky commented on platform/cc/RuntimeEffect.cc
> +    SkShader** cPtrs = reinterpret_cast<SkShader**>(childrenPtrs);
Here’s an example of a similar situation https://github.com/JetBrains/skija/blob/8b2111460148cf6f190e5a1db24cf8ebfb069dcd/platform/cc/ImageFilter.cc#L126-L139

2021-08-07 07:10 UTC, Vechro commented
I addressed all your comments as well as I could. I figure about now I should actually test if any of this works.

2021-08-07 11:24 UTC, tonsky commented
Write a scene in the examples/scenes directory, add it to Scenes.java, then test with any of examples/lwjgl, examples/kwinit or examples/jwm (they all use the same scenes). It’s not automatic (check with your eyes), but works ok

2021-08-07 16:18 UTC, Vechro commented
Okay, it's not going as smoothly as I anticipated. I may need your help figuring out the culprit here. I'm trying to recreate a simpler example of one of the examples on Skia's website, the SkSL should be correct as it works in the Skia sandbox. Yet I manage to get a `siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000000000020` when I try to recreate it as a Scene.
I've included the full error log: [hs_err_pid25196.log](https://github.com/JetBrains/skija/files/6949384/hs_err_pid25196.log). The branch now also includes the example I wrote. Any insight would be greatly appreciated.

2021-08-07 20:03 UTC, merged

2021-08-07 20:14 UTC, tonsky commented
Merged. Thanks for the contribution, from the words of Skia team at Google, I know it’s an important part of the Skia API, and finally Skija has it as well.

Also, check out the example!

2021-08-08 06:44 UTC, Vechro commented
Thank you! The example looks great!